### ISSUE TITLE
1.1.0 build doesn't work on ubuntu 19.04 (64bit pure)

### ISSUE THREAD

**Issue by bigfluffycloud** [speeduino/SpeedyLoader#4]
/tmp/.mount_SpeedyTC4BIV/resources//bin/avrdude-linux_i686/avrdude
avrdude stderr: /tmp/.mount_SpeedyTC4BIV/resources//bin/avrdude-linux_i686/avrdude: error while loading shared libraries: libusb-1.0.so.0: cannot open shared object file: No such file or directory

It appears that it wants a 686 version of the library but there are no 32bit libraries in 19.04 :O

**Comment by noisymime** [comment]
Yeah, the sae problem is coming up on MacOS shortly too. There will be a new version out in the next few weeks that contains 64-bit binaries

**Comment by bigfluffycloud** [comment]
Is there a reason you would want to avoid the host version of avrdude? I
haven't played with it much besides flashing a few arduino from time to
time so i wasn't sure if it's a compatibility thing or just easier on
the user? 

Appreciate all your hard work on speeduino! :) 

On 08.06.2019 19:37, Josh Stewart wrote:

> Yeah, the sae problem is coming up on MacOS shortly too. There will be a new version out in the next few weeks that contains 64-bit binaries 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/speeduino/SpeedyLoader/issues/4?email_source=notifications&amp;email_token=AKYOBCBFNPKJKJTFF2CII2DPZQ7DJA5CNFSM4HWIBCZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXIATBA#issuecomment-500173188
[2]

**Comment by noisymime** [comment]
> Is there a reason you would want to avoid the host version of avrdude? I haven't played with it much besides flashing a few arduino from time to time so i wasn't sure if it's a compatibility thing or just easier on the user?

It's mostly a compatibility thing. For example, if someone has used the default Ubuntu version of the Arduino IDE, which for some reason is the ancient 1.0.5 (Which was released on 2014!) then the older version of avrdude it ships with isn't compatible. The generally safest option is to bundle in a known working version, but it does mean getting . binary that will work everywhere. 

Unfortunately I can't just grab that binary that comes from somewhere like `brew` because that one is dynamically linked to a bunch of other dependencies. That's fine if you're using `brew` and it will grab them all for you, but no good for a portable binary. I'll either end up compiling my own with everything statically linked or wait for the updated version of the Arduino IDE to come out and grab it from there.

**Comment by noisymime** [comment]
This is now resolved and confirmed working in the 1.2.0 release
